version: '3.1'

services:

  vsftp:
    container_name: vsftp
    image: fauria/vsftpd
    restart: always
    ports:
      - 40020:20
      - 40021:21
      - 60000-60100:60000-60100
    environment:
      FTP_USER: dispute-ftp
      FTP_PASS: 52CXU94OUtHG 
      PASV_ADDRESS: 192.168.209.128
      PASV_MIN_PORT: 60000
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - ./dispute-ftp:/home/vsftpd
