version: '3.1'

services:

  mysql_5_7:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - ./conf:/etc/mysql/conf.d
      - ./data:/var/lib/mysql


